[package]
name = "sim-render"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "simcraft-view"
path = "src/bin/simcraft-view.rs"

[dependencies]
sim-core.workspace = true
sim-rules.workspace = true
sim-state.workspace = true
serde.workspace = true
ron.workspace = true
crossterm = "0.29"
