#!/usr/bin/env python3
"""Lay out a 1.5-mile quad-oval from Charlotte Motor Speedway's published figures and write tracks/charlotte.ron.

Published (charlottemotorspeedway.com, Track Facts): 1.5 mi (7,920 ft); frontstretch 1,980 ft, backstretch 1,500 ft;
turns 1-2 2,400 ft long with a 685 ft radius, turns 3-4 2,040 ft with 625 ft; turns banked 24°, straights 5°.
A turn is longer than a half circle of its radius: the radius is the tightest part, and real turns sweep in and out
wider (transition spirals). So each turn here is a wider entry arc (ENTRY × the radius), the published radius in the
middle, and a matching exit, sized to the published turn length. Not published: the shape of the quad-oval's dogleg.
Here it is one gentle left bend of radius DOGLEG_R at the start/finish line; its angle and the straights either side
are solved so the lap closes with the published frontstretch length. Charlotte's lengths, radii and banking on an
approximate plan, not a survey of the real track.

    games/race/gen_track.py            # writes games/race/tracks/charlotte.ron
"""

import math
from pathlib import Path

FT = 0.3048
LAP = 1.5 * 1609.344
R12, R34 = 685 * FT, 625 * FT
BACK = 1500 * FT
FRONT = 1980 * FT
L12, L34 = 2400 * FT, 2040 * FT
ENTRY = 1.6
DOGLEG_R = 300.0
WIDTH = 18.0  # m, assumed (not published)
TURN_BANK, STRAIGHT_BANK = 24.0, 5.0
BLEND = 120.0


def walk(segs):
    """End point and heading of segments laid from (0, 0) heading 0: ("S", len) or ("L", radius, radians)."""
    x = y = h = 0.0
    for s in segs:
        if s[0] == "S":
            x += s[1] * math.cos(h)
            y += s[1] * math.sin(h)
        else:
            r, a = s[1], s[2]
            cx, cy = x - r * math.sin(h), y + r * math.cos(h)
            h += a
            x, y = cx + r * math.sin(h), cy - r * math.cos(h)
    return x, y, h


def turn(radius, length, k):
    """Entry, apex and exit arcs turning π - k in all, `length` long, tightest at `radius`."""
    wide = ENTRY * radius
    apex = (length - wide * (math.pi - k)) / (radius - wide)
    entry = (math.pi - k - apex) / 2
    assert 0 < apex < math.pi - k, (radius, length, k, apex)
    return [("L", wide, entry), ("L", radius, apex), ("L", wide, entry)]


def layout(a, b, k):
    return ([("L", DOGLEG_R, k), ("S", b)] + turn(R12, L12, k) + [("S", BACK)] + turn(R34, L34, k)
            + [("S", a), ("L", DOGLEG_R, k)])


def straights(k):
    """For a dogleg angle k, the two frontstretch straights that close the lap: the end point is linear in them."""
    x0, y0, _ = walk(layout(0.0, 0.0, k))
    # b runs at heading k, a at heading -k (they only add (a+b)cos k, (b-a) sin k): solve for x = y = 0.
    total = -x0 / math.cos(k)
    diff = -y0 / math.sin(k)
    return (total - diff) / 2, (total + diff) / 2


def front(k):
    a, b = straights(k)
    return a + b + 2 * DOGLEG_R * k


def solve():
    # The frontstretch lengthens as the dogleg sharpens; bisect for the published length.
    lo, hi = 0.02, 0.6
    for _ in range(200):
        mid = (lo + hi) / 2
        if front(mid) < FRONT:
            lo = mid
        else:
            hi = mid
    k = (lo + hi) / 2
    a, b = straights(k)
    return a, b, k


def main():
    a, b, k = solve()
    assert a > 0 and b > 0 and 0 < k < 0.5, (a, b, k)
    mm = lambda m: round(m * 1000)
    cd = lambda rad: round(math.degrees(rad) * 100)
    names = ["Tri-oval (start/finish)", "Frontstretch", "Turn 1", "Turns 1-2", "Turn 2", "Backstretch", "Turn 3",
             "Turns 3-4", "Turn 4", "Frontstretch", "Tri-oval"]
    segs = []
    for piece, name in zip(layout(a, b, k), names):
        bank = TURN_BANK if name.startswith("Turn") else STRAIGHT_BANK
        if piece[0] == "S":
            segs.append(("Straight", piece[1], None, bank, name))
        else:
            segs.append(("Left", piece[1], piece[2], bank, name))
    lines = []
    for shape, r, ang, bank, name in segs:
        s = f"Straight({mm(r)})" if shape == "Straight" else f"Left({mm(r)}, {cd(ang)})"
        lines.append(f'        (shape: {s}, bank: {round(bank * 100)}, name: "{name}"),')
    out = Path(__file__).parent / "tracks" / "charlotte.ron"
    out.parent.mkdir(exist_ok=True)
    out.write_text(
        "// Generated by games/race/gen_track.py: Charlotte Motor Speedway's published length, radii and banking on an\n"
        "// approximate plan (the dogleg's shape is not published). Millimetres and hundredths of a degree.\n"
        "(\n"
        '    name: "1.5-mile quad-oval (Charlotte dimensions)",\n'
        f"    width: {mm(WIDTH)},\n"
        "    start: (0, 0, 0),\n"
        f"    blend: {mm(BLEND)},\n"
        "    segments: [\n" + "\n".join(lines) + "\n    ],\n)\n"
    )
    lap = sum(p[1] if p[0] == "S" else p[1] * p[2] for p in layout(a, b, k))
    print(f"lap {lap:.1f} m (published {LAP:.1f}); frontstretch straights {a:.1f} + {b:.1f} m, "
          f"dogleg {math.degrees(2 * k):.1f}°; wrote {out}")


if __name__ == "__main__":
    main()
